// <auto-generated />
namespace SmartGameStatTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TeamID_in_BoxScore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamID_in_BoxScore));
        
        string IMigrationMetadata.Id
        {
            get { return "201811211427412_TeamID_in_BoxScore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
