// <auto-generated />
namespace SmartGameStatTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class audio_file_contents_test21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(audio_file_contents_test21));
        
        string IMigrationMetadata.Id
        {
            get { return "201904022144557_audio_file_contents_test21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
