// <auto-generated />
namespace SmartGameStatTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Game_Create_Fix_Test_Undo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Game_Create_Fix_Test_Undo));
        
        string IMigrationMetadata.Id
        {
            get { return "201903262157231_Game_Create_Fix_Test_Undo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
