// <auto-generated />
namespace SmartGameStatTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GameID_to_Games_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameID_to_Games_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201904092132551_GameID_to_Games_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
