// <auto-generated />
namespace SmartGameStatTrackingWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Profiles_Schema_Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Profiles_Schema_Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201902262245510_Profiles_Schema_Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
